(() => {
  'use strict';

  const DB_NAME = 'activity10LocalDB';
  const DB_VERSION = 1;
  const STORE_NAME = 'state';
  const STATE_KEY = 'main';

  const gradeDefinitions = {
    primary: [['p1','الأول الابتدائي'],['p2','الثاني الابتدائي'],['p3','الثالث الابتدائي'],['p4','الرابع الابتدائي'],['p5','الخامس الابتدائي'],['p6','السادس الابتدائي']],
    middle: [['m1','الأول المتوسط'],['m2','الثاني المتوسط'],['m3','الثالث المتوسط']],
    secondary: [['s1','الأول الثانوي'],['s2','الثاني الثانوي'],['s3','الثالث الثانوي']]
  };

  const stageLabels = {
    primary: { name: 'المرحلة الابتدائية', short: 'ابتدائي', hint: 'الصفوف من الأول إلى السادس' },
    middle: { name: 'المرحلة المتوسطة', short: 'متوسط', hint: 'الصفوف من الأول إلى الثالث' },
    secondary: { name: 'المرحلة الثانوية', short: 'ثانوي', hint: 'يتطلب المسار والفصل الدراسي' }
  };

  const PLAN = {
    primary: {
      general: {
        p1: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':8,'الرياضيات':5,'العلوم':3,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:3, total:33 },
        p2: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':7,'الرياضيات':6,'العلوم':3,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:3, total:33 },
        p3: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':6,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:3, total:33 },
        p4: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:2, total:33 },
        p5: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:2, total:33 },
        p6: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:2, total:33 }
      },
      tahfiz: {
        p1: { subjects: {'القرآن الكريم والدراسات الإسلامية':9,'اللغة العربية':8,'الرياضيات':5,'العلوم':3,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:1, total:35 },
        p2: { subjects: {'القرآن الكريم والدراسات الإسلامية':9,'اللغة العربية':7,'الرياضيات':6,'العلوم':3,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:1, total:35 },
        p3: { subjects: {'القرآن الكريم والدراسات الإسلامية':9,'اللغة العربية':6,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':3,'المهارات الحياتية والأسرية':1}, activity:1, total:35 },
        p4: { subjects: {'القرآن الكريم والدراسات الإسلامية':8,'التجويد':1,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:0, total:35 },
        p5: { subjects: {'القرآن الكريم والدراسات الإسلامية':8,'التجويد':1,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:0, total:35 },
        p6: { subjects: {'القرآن الكريم والدراسات الإسلامية':8,'التجويد':1,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':3,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:0, total:35 }
      }
    },
    middle: {
      general: {
        m1: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':5,'الدراسات الاجتماعية':3,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:1, total:35 },
        m2: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':5,'الدراسات الاجتماعية':3,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1}, activity:1, total:35 },
        m3: { subjects: {'القرآن الكريم والدراسات الإسلامية':5,'اللغة العربية':4,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':2,'التربية البدنية والدفاع عن النفس':2,'المهارات الحياتية والأسرية':1,'التفكير الناقد':2}, activity:1, total:35 }
      },
      tahfiz: {
        m1: { subjects: {'القرآن الكريم والدراسات الإسلامية':8,'التجويد':1,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':1,'المهارات الحياتية والأسرية':1}, activity:0, total:35 },
        m2: { subjects: {'القرآن الكريم والدراسات الإسلامية':8,'التجويد':1,'اللغة العربية':5,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':1,'المهارات الحياتية والأسرية':1}, activity:0, total:35 },
        m3: { subjects: {'القرآن الكريم والدراسات الإسلامية':7,'التجويد':1,'اللغة العربية':4,'الدراسات الاجتماعية':2,'الرياضيات':6,'العلوم':4,'اللغة الإنجليزية':4,'المهارات الرقمية':2,'التربية الفنية':1,'التربية البدنية والدفاع عن النفس':1,'المهارات الحياتية والأسرية':1,'التفكير الناقد':2}, activity:0, total:35 }
      }
    }
  };

  const RANKS = { practitioner:'معلم ممارس', advanced:'معلم متقدم', expert:'معلم خبير' };
  const specialtyAliases = new Map([
    ['دين','دراسات إسلامية'],['دراسات اسلامية','دراسات إسلامية'],['اسلاميات','دراسات إسلامية'],['إسلاميات','دراسات إسلامية'],['تربية اسلامية','دراسات إسلامية'],
    ['قرآن','القرآن الكريم والدراسات الإسلامية'],['قران','القرآن الكريم والدراسات الإسلامية'],['تحفيظ','القرآن الكريم والدراسات الإسلامية'],
    ['رياضيات','رياضيات'],['الرياضيات','رياضيات'],['عربي','لغة عربية'],['لغة عربية','لغة عربية'],['اللغه العربيه','لغة عربية'],
    ['علوم','علوم'],['العلوم','علوم'],['انجليزي','لغة إنجليزية'],['إنجليزي','لغة إنجليزية'],['لغة انجليزية','لغة إنجليزية'],
    ['اجتماعيات','دراسات اجتماعية'],['دراسات اجتماعية','دراسات اجتماعية'],['حاسب','مهارات رقمية'],['حاسوب','مهارات رقمية'],['مهارات رقمية','مهارات رقمية'],
    ['بدنية','تربية بدنية'],['تربية بدنية','تربية بدنية'],['فنية','تربية فنية'],['تربية فنية','تربية فنية'],['تجويد','تجويد'],['تفكير ناقد','تفكير ناقد'],['صفوف اولية','صفوف أولية'],['صفوف أولية','صفوف أولية']
  ]);

  const defaultState = () => ({
    version: 3,
    settings: { schoolName:'', gender:'', stages:{primary:{enabled:false,type:'general'},middle:{enabled:false,type:'general'},secondary:{enabled:false,type:'general'}}, gradeSections:{}, regularPeriods:35, targetLoad:24, weeks:36, activityWeekly:1, currentStep:1 },
    teachers: [], importPreview: [], validation:{teachers:[],sections:[]}, distributions:[], selectedTeacherId:null, currentView:'dashboard', lastSavedAt:null
  });

  let state = defaultState();
  let db;
  let storageMode = 'indexeddb';
  let saveTimer;
  let toastTimer;
  let pendingWorkbook = null;

  const $ = (s,r=document) => r.querySelector(s);
  const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const uid = (p='id') => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const ar = (v) => Number(v||0).toLocaleString('ar-SA');
  const safe = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clean = (v='') => String(v).trim().replace(/\s+/g,' ');
  const key = (v='') => clean(v).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي');
  const canonicalSpecialty = (v='') => {
    const raw=clean(v); if(!raw) return '';
    for(const [a,c] of specialtyAliases) if(key(a)===key(raw)) return c;
    return raw;
  };

  function mergeState(saved){
    const base=defaultState();
    const merged={...base,...(saved||{}),settings:{...base.settings,...(saved?.settings||{}),stages:{...base.settings.stages,...(saved?.settings?.stages||{})},gradeSections:{...(saved?.settings?.gradeSections||{})}}};
    merged.teachers=(Array.isArray(saved?.teachers)?saved.teachers:[]).map(t=>({id:t.id||uid('teacher'),name:t.name||'',specialty:t.specialty||'',load:t.load==null||t.load===''?null:Number(t.load),rank:t.rank||'practitioner',excluded:Boolean(t.excluded),assignments:Array.isArray(t.assignments)?t.assignments:[]}));
    merged.importPreview=Array.isArray(saved?.importPreview)?saved.importPreview:[];
    merged.validation=saved?.validation&& !Array.isArray(saved.validation)?saved.validation:{teachers:[],sections:[]};
    merged.distributions=Array.isArray(saved?.distributions)?saved.distributions:[];
    return merged;
  }

  function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE_NAME))q.result.createObjectStore(STORE_NAME)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
  function readState(){if(storageMode==='localstorage'){try{return Promise.resolve(JSON.parse(localStorage.getItem('activity10State')||'null'))}catch{return Promise.resolve(null)}}return new Promise((res,rej)=>{const q=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).get(STATE_KEY);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
  function persist(){state.lastSavedAt=new Date().toISOString();if(storageMode==='localstorage'){localStorage.setItem('activity10State',JSON.stringify(state));return Promise.resolve()}return new Promise((res,rej)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).put(state,STATE_KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  function scheduleSave(msg='تم الحفظ محليًا'){clearTimeout(saveTimer);$('#saveStatus').textContent='جارٍ الحفظ…';saveTimer=setTimeout(async()=>{try{await persist();$('#saveStatus').textContent=msg}catch(e){console.error(e);$('#saveStatus').textContent='تعذر الحفظ'}},180)}
  function toast(msg,type=''){const el=$('#toast');el.textContent=msg;el.className=`toast show ${type}`.trim();clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='toast',2800)}

  function enabledStages(){return Object.entries(state.settings.stages).filter(([,v])=>v.enabled).map(([k])=>k)}
  function allGrades(){return enabledStages().flatMap(stage=>gradeDefinitions[stage].map(([id,label])=>({id,label,stage})))}
  function allSections(){return allGrades().flatMap(g=>Array.from({length:Number(state.settings.gradeSections[g.id]||0)},(_,i)=>({id:`${g.id}_${i+1}`,gradeId:g.id,gradeLabel:g.label,stage:g.stage,number:i+1,label:`${g.label}/${i+1}`})))}
  function sectionById(id){return allSections().find(s=>s.id===id)}
  function planForGrade(gradeId){const stage=gradeId?.startsWith('p')?'primary':gradeId?.startsWith('m')?'middle':gradeId?.startsWith('s')?'secondary':null;if(!stage)return null;const type=state.settings.stages[stage]?.type||'general';return PLAN[stage]?.[type]?.[gradeId]||null}
  function periodsFor(sectionId,subject){const section=sectionById(sectionId);const plan=section?planForGrade(section.gradeId):null;return Number(plan?.subjects?.[subject]||0)}
  function subjectsForSection(sectionId){const section=sectionById(sectionId);const plan=section?planForGrade(section.gradeId):null;return plan?Object.keys(plan.subjects):[]}
  function assignmentCapacity(a){return Math.floor(Number(a.weeklyPeriods||0)*Number(state.settings.weeks||36)*.10+1e-9)}
  function teacherLoad(t){return (t.assignments||[]).reduce((s,a)=>s+Number(a.weeklyPeriods||0),0)}
  function targetAnnual(){return Number(state.settings.activityWeekly||1)*Number(state.settings.weeks||36)}
  function settingsComplete(){return Boolean(state.settings.schoolName&&state.settings.gender&&enabledStages().length&&allSections().length)}
  function teacherComplete(t){return Boolean(t.name&&t.specialty&&Number(t.load)>0&&(t.assignments||[]).length&&teacherLoad(t)===Number(t.load))}

  function viewTitle(v){return {dashboard:'مركز القيادة',settings:'إعداد المدرسة',import:'استيراد المعلمين',classify:'إسناد المواد والفصول',validate:'التحقق من البيانات',distribution:'توزيع حصة النشاط'}[v]||'موزّع حصة النشاط'}
  function navigate(v){state.currentView=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=viewTitle(v);if(v==='dashboard')renderDashboard();if(v==='settings')renderSettings();if(v==='import')renderImport();if(v==='classify')renderTeachers();if(v==='validate')renderValidation();if(v==='distribution')renderDistributions();updateTopbar();updateNav();closeMobile();scheduleSave()}
  function updateTopbar(){const stageText=enabledStages().map(k=>stageLabels[k].short).join('، ');$('#schoolNameTop').textContent=state.settings.schoolName||'مدرسة جديدة';$('#schoolMetaTop').textContent=stageText||'لم تكتمل الإعدادات';$('#quickContinueBtn').textContent=settingsComplete()?'متابعة المشروع':'متابعة الإعداد'}
  function updateNav(){const completeTeachers=state.teachers.length&&state.teachers.every(t=>t.excluded||teacherComplete(t));const val=state.validation?.teachers?.length;const map={dashboard:'complete',settings:settingsComplete()?'complete':(state.settings.schoolName||enabledStages().length?'warning':''),import:state.teachers.length?'complete':'',classify:completeTeachers?'complete':(state.teachers.length?'warning':''),validate:val?(state.validation.teachers.every(x=>['eligible','excluded'].includes(x.status))?'complete':'warning'):'',distribution:state.distributions.length?'complete':''};$$('[data-step-state]').forEach(el=>{const s=map[el.dataset.stepState]||'';el.className=`nav-state ${s}`.trim();el.textContent=s?'●':'○'})}

  function renderDashboard(){
    const active=state.teachers.filter(t=>!t.excluded);const complete=active.filter(teacherComplete).length;
    const eligibleSections=allSections().filter(s=>planForGrade(s.gradeId)?.activity===0).length;
    $('#statTeachers').textContent=ar(state.teachers.length);$('#statComplete').textContent=ar(complete);$('#statEligible').textContent=ar(eligibleSections);$('#statReview').textContent=ar(active.length-complete);
    const flags=[settingsComplete(),state.teachers.length>0,complete===active.length&&active.length>0,state.validation?.teachers?.length>0,state.distributions.length>0];const progress=Math.round(flags.filter(Boolean).length/flags.length*100);$('#progressPercent').textContent=`${ar(progress)}٪`;$('#progressBar').style.width=`${progress}%`;
    const steps=[['إعداد المدرسة','الهوية والمراحل والشعب',flags[0]],['استيراد المعلمين','الأسماء والتخصصات والأنصبة',flags[1]],['إسناد المواد والفصول','الحصص تُقرأ تلقائيًا من الدليل',flags[2]],['التحقق','فحص النصاب ورصيد كل فصل',flags[3]],['التوزيع','اختيار المادة المختصر منها لكل فصل',flags[4]];
    $('#workflowSteps').innerHTML=steps.map((s,i)=>`<div class="workflow-step ${s[2]?'complete':''}"><span class="step-index">${ar(i+1)}</span><div><strong>${s[0]}</strong><small>${s[1]}</small></div><span class="step-status">${s[2]?'مكتملة':'قيد الإعداد'}</span></div>`).join('');
  }

  function showSettingsStep(step,persistIt=true){step=Math.max(1,Math.min(4,Number(step)));state.settings.currentStep=step;$$('.settings-step-panel').forEach(x=>x.classList.toggle('active',Number(x.dataset.settingsPanel)===step));$$('.wizard-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.settingsStep)===step));$('#settingsPrevBtn').disabled=step===1;$('#settingsNextBtn').textContent=step===4?'حفظ وإنهاء':'التالي';if(persistIt)scheduleSave()}
  function renderSettings(){
    $('#schoolNameInput').value=state.settings.schoolName||'';$$('[data-choice="gender"]').forEach(b=>b.classList.toggle('selected',b.dataset.value===state.settings.gender));$('#regularPeriodsInput').value=state.settings.regularPeriods;$('#targetLoadInput').value=state.settings.targetLoad;$('#weeksInput').value=state.settings.weeks;$('#activityWeeklyInput').value=state.settings.activityWeekly;
    $('#stageCards').innerHTML=Object.entries(stageLabels).map(([k,m])=>{const st=state.settings.stages[k];return `<article class="stage-card ${st.enabled?'active':''}" data-stage-card="${k}"><div class="stage-card-head"><div><h3>${m.name}</h3><p>${m.hint}</p></div><button class="stage-toggle" data-toggle-stage="${k}" aria-label="تفعيل المرحلة"></button></div><div class="education-types"><button class="type-button ${st.type==='general'?'selected':''}" data-stage-type="${k}" data-type="general">تعليم عام</button><button class="type-button ${st.type==='tahfiz'?'selected':''}" data-stage-type="${k}" data-type="tahfiz">تحفيظ القرآن</button></div></article>`}).join('');
    const grades=allGrades();const root=$('#gradesEditor');if(!grades.length){root.className='grades-editor empty-state';root.innerHTML='<div class="empty-icon">▦</div><h3>اختر مرحلة تعليمية أولًا</h3><p>بعد اختيار المرحلة سيظهر عدد الشعب لكل صف.</p>'}else{root.className='grades-editor';root.innerHTML=grades.map(g=>{const count=Number(state.settings.gradeSections[g.id]||0);const chips=Array.from({length:count},(_,i)=>`<span class="section-chip">${g.label}/${i+1}</span>`).join('');return `<div class="grade-row"><div><strong>${g.label}</strong><small>${stageLabels[g.stage].name}</small></div><label class="field"><span>عدد الشعب</span><input type="number" min="0" max="20" value="${count}" data-grade-count="${g.id}"></label><div class="sections-preview">${chips||'<span class="status-chip status-neutral">لم تُنشأ شعب</span>'}</div></div>`}).join('')}
    renderDiagnostic();showSettingsStep(state.settings.currentStep||1,false);
  }
  function renderDiagnostic(){const root=$('#liveEligibilityDiagnostic');if(!root)return;const sections=allSections();const auto=sections.filter(s=>planForGrade(s.gradeId));const need=sections.filter(s=>planForGrade(s.gradeId)?.activity===0);const unsupported=sections.filter(s=>!planForGrade(s.gradeId));const items=[{ok:Number(state.settings.regularPeriods)===35,title:'٣٥ حصة نظامية',text:'ضابط التشغيل المعتمد في المشروع.'},{ok:Number(state.settings.targetLoad)===24,title:'نصاب ٢٤ حصة',text:'النصاب المستهدف للمعلمين.'},{ok:Number(state.settings.weeks)===36&&Number(state.settings.activityWeekly)===1,title:'٣٦ حصة نشاط سنويًا',text:'حصة نشاط واحدة لكل فصل أسبوعيًا.'},{ok:auto.length>0&&unsupported.length===0,title:'ربط الدليل',text:unsupported.length?`${ar(unsupported.length)} فصل ثانوي يحتاج تحديد المسار والفصل الدراسي.`:`${ar(auto.length)} فصل مرتبط آليًا، منها ${ar(need.length)} يحتاج توزيع نسبة ١٠٪.`}];root.innerHTML=items.map(x=>`<article class="diagnostic-item ${x.ok?'pass':'attention'}"><span class="diagnostic-icon">${x.ok?'✓':'!'}</span><strong>${x.title}</strong><small>${x.text}</small></article>`).join('')}
  function validateSettings(step){if(step===1&&!clean(state.settings.schoolName))return'أدخل اسم المدرسة.';if(step===1&&!state.settings.gender)return'حدد بنين أو بنات.';if(step===2&&!enabledStages().length)return'اختر مرحلة واحدة على الأقل.';if(step===3&&!allSections().length)return'أدخل عدد الشعب.';return''}

  function detectName(parts){if(/^Tea_/i.test(parts[0]||'')&&parts[1])return parts[1];const blocked=['دائم','معلم','معلمة','متعاقد','على رأس العمل'];return parts.find(v=>{const t=clean(v);return t.split(' ').length>=3&&/[\u0600-\u06FF]/.test(t)&&!blocked.includes(t)&&!specialtyAliases.has(t)})||parts[0]||''}
  function detectSpecialty(parts,name){for(const p of parts){const raw=clean(p);if(!raw||raw===name)continue;const c=canonicalSpecialty(raw);if(c!==raw||[...specialtyAliases.values()].includes(c))return c}return''}
  function detectLoad(parts){for(const p of parts){const raw=clean(p);if(!/^\d{1,2}$/.test(raw))continue;const n=Number(raw);if(n>=1&&n<=40)return n}return null}
  function parseText(text){return text.split(/\r?\n/).map(clean).filter(Boolean).map((line,i)=>{const parts=line.includes('\t')?line.split('\t').map(clean):line.includes('|')?line.split('|').map(clean):line.split(',').map(clean);const name=detectName(parts);const specialty=detectSpecialty(parts,name);const load=detectLoad(parts);return{tempId:uid('preview'),row:i+1,name,specialty,load,status:!name?'error':!specialty||!load?'warning':'complete'}}).filter(x=>x.name)}
  function renderImport(){renderImportPreview()}
  function renderImportPreview(){const p=state.importPreview||[];$('#previewCount').textContent=`${ar(p.length)} سجل`;$('#clearPreviewBtn').disabled=!p.length;$('#commitImportBtn').disabled=!p.length||p.some(x=>!x.name||!x.specialty||!Number(x.load));const root=$('#importPreview');if(!p.length){root.className='table-wrap empty-table';root.innerHTML='<div class="empty-icon">▤</div><h3>لم يتم تحميل بيانات بعد</h3><p>ستظهر المعاينة قبل اعتماد الاستيراد.</p>';updatePreviewQuality();return}root.className='table-wrap';root.innerHTML=`<table class="data-table"><thead><tr><th>#</th><th>اسم المعلم</th><th>التخصص</th><th>النصاب</th><th>الحالة</th></tr></thead><tbody>${p.map((x,i)=>`<tr><td>${ar(i+1)}</td><td><input class="inline-input" data-preview-field="name" data-preview-id="${x.tempId}" value="${safe(x.name)}"></td><td><input class="inline-input" list="specialtyOptions" data-preview-field="specialty" data-preview-id="${x.tempId}" value="${safe(x.specialty)}" placeholder="اكتب التخصص"></td><td><input class="inline-input number" type="number" min="1" max="40" data-preview-field="load" data-preview-id="${x.tempId}" value="${x.load??''}" placeholder="اكتب النصاب"></td><td>${previewChip(x)}</td></tr>`).join('')}</tbody></table>`;updatePreviewQuality()}
  function previewChip(x){if(!x.name)return'<span class="status-chip status-error">اسم غير صالح</span>';if(!x.specialty)return'<span class="status-chip status-warning">التخصص مطلوب</span>';if(!Number(x.load))return'<span class="status-chip status-warning">اكتب النصاب</span>';return'<span class="status-chip status-complete">مكتمل</span>'}
  function updatePreviewQuality(){const b=$('#previewQualityBadge');if(!b)return;const p=state.importPreview||[];if(!p.length){b.className='quality-badge';b.textContent='بانتظار البيانات';return}const missing=p.filter(x=>!x.name||!x.specialty||!Number(x.load)).length;const seen=new Set();let dup=0;p.forEach(x=>{const k=key(x.name);if(k&&seen.has(k))dup++;seen.add(k)});if(!missing&&!dup){b.className='quality-badge good';b.textContent=`جاهزة للاعتماد · ${ar(p.length)} سجل`}else{b.className='quality-badge warning';b.textContent=`${missing?`${ar(missing)} ناقص`:''}${missing&&dup?' · ':''}${dup?`${ar(dup)} مكرر`:''}`}}
  function commitImport(){if(state.importPreview.some(x=>!x.name||!x.specialty||!Number(x.load)))return toast('أكمل التخصص والنصاب لجميع المعلمين.','warning');let added=0;state.importPreview.forEach(x=>{const ex=state.teachers.find(t=>key(t.name)===key(x.name));if(ex){ex.specialty=canonicalSpecialty(x.specialty);ex.load=Number(x.load)}else{state.teachers.push({id:uid('teacher'),name:clean(x.name),specialty:canonicalSpecialty(x.specialty),load:Number(x.load),rank:'practitioner',excluded:false,assignments:[]});added++}});state.importPreview=[];renderImportPreview();renderDashboard();updateNav();scheduleSave();toast(`تم اعتماد ${ar(added)} معلمًا جديدًا`,'success');navigate('classify')}

  function matrixFromFile(file){return new Promise(async(res,rej)=>{try{if(!window.XLSX)throw new Error('تعذر تحميل قارئ Excel. استخدم CSV أو النص المباشر.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sh=wb.Sheets[wb.SheetNames[0]];res(XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false}))}catch(e){rej(e)}})}
  async function openMapping(file){try{const matrix=await matrixFromFile(file);const rows=matrix.map(r=>r.map(clean)).filter(r=>r.some(Boolean));if(rows.length<2)throw new Error('الملف لا يحتوي على بيانات.');pendingWorkbook={file,headers:rows[0],rows:rows.slice(1)};$('#mappingFileName').textContent=file.name;$('#mappingRowsCount').textContent=`${ar(pendingWorkbook.rows.length)} صف`;fillMap($('#mapNameColumn'),pendingWorkbook.headers,['اسم المعلم','المعلم','الاسم','name'],false);fillMap($('#mapSpecialtyColumn'),pendingWorkbook.headers,['التخصص','تخصص','مادة التخصص','subject'],true);fillMap($('#mapLoadColumn'),pendingWorkbook.headers,['النصاب','الحصص','load'],true);renderMapSample();$('#columnMappingModal').showModal()}catch(e){console.error(e);toast(e.message||'تعذر قراءة الملف','error')}}
  function fillMap(select,headers,patterns,optional){const idx=headers.findIndex(h=>patterns.some(p=>key(h).includes(key(p))));select.innerHTML=`<option value="">${optional?'غير موجود / إدخال لاحق':'اختر العمود'}</option>`+headers.map((h,i)=>`<option value="${i}">${safe(h||`العمود ${i+1}`)}</option>`).join('');select.value=idx>=0?String(idx):''}
  function renderMapSample(){if(!pendingWorkbook)return;const n=$('#mapNameColumn').value,s=$('#mapSpecialtyColumn').value,l=$('#mapLoadColumn').value;$('#mappingSample').innerHTML=`<table><thead><tr><th>اسم المعلم</th><th>التخصص</th><th>النصاب</th></tr></thead><tbody>${pendingWorkbook.rows.slice(0,5).map(r=>`<tr><td>${safe(n===''?'':r[Number(n)])}</td><td>${safe(s===''?'':canonicalSpecialty(r[Number(s)]))}</td><td>${safe(l===''?'إدخال يدوي':r[Number(l)])}</td></tr>`).join('')}</tbody></table>`}
  function confirmMapping(){if(!pendingWorkbook)return;const n=$('#mapNameColumn').value,s=$('#mapSpecialtyColumn').value,l=$('#mapLoadColumn').value;if(n==='')return toast('حدد عمود اسم المعلم.','warning');state.importPreview=pendingWorkbook.rows.map((r,i)=>{const name=clean(r[Number(n)]||'');const specialty=s===''?'':canonicalSpecialty(r[Number(s)]||'');const load=l===''?null:detectLoad([r[Number(l)]]);return{tempId:uid('preview'),row:i+1,name,specialty,load,status:!name?'error':!specialty||!load?'warning':'complete'}}).filter(x=>x.name);pendingWorkbook=null;$('#columnMappingModal').close();renderImportPreview();scheduleSave();toast(`تمت قراءة ${ar(state.importPreview.length)} سجلًا`,'success')}

  function filteredTeachers(){const q=key($('#teacherSearch')?.value||'');return q?state.teachers.filter(t=>key(`${t.name} ${t.specialty}`).includes(q)):state.teachers}
  function renderTeachers(){const list=filteredTeachers();$('#teachersListCount').textContent=ar(state.teachers.length);const root=$('#teachersList');if(!state.teachers.length){root.innerHTML='<div class="empty-state"><div class="empty-icon">⇩</div><h3>لا يوجد معلمون</h3><p>استورد المعلمين أولًا.</p></div>';$('#teacherEditor').className='panel teacher-editor empty-state';$('#teacherEditor').innerHTML='<div class="empty-icon">◫</div><h3>استورد المعلمين لبدء الإسناد</h3>';return}root.innerHTML=list.map(t=>{const initials=t.name.split(' ').slice(0,2).map(x=>x[0]).join('');const load=teacherLoad(t);return`<button class="teacher-list-item ${state.selectedTeacherId===t.id?'active':''} ${t.excluded?'teacher-excluded':''}" data-select-teacher="${t.id}"><span class="teacher-mini-avatar">${safe(initials)}</span><span><strong>${safe(t.name)}</strong><small>${safe(t.specialty||'التخصص غير محدد')} · ${ar(load)}/${ar(t.load||0)} · ${safe(RANKS[t.rank])}</small></span><span class="teacher-status-dot ${t.excluded?'excluded':teacherComplete(t)?'complete':'warning'}"></span></button>`}).join('');if(state.selectedTeacherId&&state.teachers.some(t=>t.id===state.selectedTeacherId))renderTeacherEditor(state.selectedTeacherId);else if(list[0])selectTeacher(list[0].id)}
  function selectTeacher(id){state.selectedTeacherId=id;renderTeachers();scheduleSave()}
  function renderTeacherEditor(id){const t=state.teachers.find(x=>x.id===id);if(!t)return;const root=$('#teacherEditor');root.className='panel teacher-editor';const load=teacherLoad(t);const sections=allSections();root.innerHTML=`<div class="teacher-editor-content">
    <div class="teacher-profile-head"><div class="teacher-avatar">${safe(t.name.split(' ').slice(0,2).map(x=>x[0]).join(''))}</div><div class="teacher-main-info"><span class="section-kicker">بيانات المعلم وإسناداته</span><h2>${safe(t.name)}</h2><p>${safe(t.specialty||'التخصص غير محدد')}</p></div><div class="load-meter"><div class="load-circle ${load===Number(t.load)?'complete':''}"><strong>${ar(load)}</strong><small>/ ${ar(t.load||0)}</small></div><span>النصاب المسند</span></div></div>
    <div class="form-grid teacher-meta-grid"><label class="field"><span>اسم المعلم</span><input data-teacher-field="name" value="${safe(t.name)}"></label><label class="field"><span>التخصص</span><input data-teacher-field="specialty" list="specialtyOptions" value="${safe(t.specialty)}"></label><label class="field"><span>النصاب</span><input data-teacher-field="load" type="number" min="1" max="40" value="${t.load??''}"></label><label class="field"><span>الرتبة</span><select data-teacher-field="rank">${Object.entries(RANKS).map(([k,v])=>`<option value="${k}" ${t.rank===k?'selected':''}>${v}</option>`).join('')}</select></label></div>
    <label class="exclude-teacher-switch"><input data-teacher-field="excluded" type="checkbox" ${t.excluded?'checked':''}><span></span><div><strong>استثناء المعلم من توزيع النشاط</strong><small>تبقى إسناداته محفوظة، ولا تُستخدم حصصه كمصدر لحصة النشاط.</small></div></label>
    <section class="smart-assignment-panel"><div class="subsection-heading"><div><h3>إضافة مادة وفصل</h3><p>اختر الفصل والمادة؛ يظهر عدد الحصص تلقائيًا من الخطة الدراسية.</p></div><span class="guide-badge">مرتبط بالدليل</span></div><div class="smart-assignment-controls"><label class="field"><span>الفصل والشعبة</span><select id="autoSectionSelect"><option value="">اختر الفصل</option>${sections.map(s=>`<option value="${s.id}">${safe(s.label)}</option>`).join('')}</select></label><label class="field"><span>المادة</span><select id="autoSubjectSelect" disabled><option value="">اختر الفصل أولًا</option></select></label><div id="autoPeriodsPreview" class="auto-periods-preview empty"><span>الحصص</span><strong>—</strong><small>تظهر تلقائيًا</small></div><button id="addAutoAssignmentBtn" class="primary-button" disabled>إضافة المادة والفصل</button></div></section>
    <section class="classification-section"><div class="subsection-heading"><div><h3>الإسنادات المسجلة</h3><p>الحصص الأسبوعية والسنوية وحد ١٠٪ محسوبة آليًا.</p></div><span class="small-badge">${ar(t.assignments.length)} إسناد</span></div><div id="teacherAssignmentsTable" class="table-wrap compact-table">${renderAssignments(t)}</div></section>
    <div class="teacher-editor-actions"><button data-action="delete-teacher" class="danger-ghost-button">حذف المعلم</button><button data-action="save-teacher" class="primary-button">حفظ بيانات المعلم</button></div>
  </div>`}
  function renderAssignments(t){if(!t.assignments.length)return'<div class="assignment-empty-state"><div class="empty-icon">＋</div><h3>لم تُضف مواد وفصول لهذا المعلم</h3><p>اختر الفصل والمادة أعلاه، وسيحدد النظام عدد الحصص تلقائيًا.</p></div>';return`<table class="data-table"><thead><tr><th>المادة</th><th>الفصل</th><th>الأسبوعي</th><th>السنوي</th><th>حد ١٠٪</th><th>عند تحويل حصة</th><th></th></tr></thead><tbody>${t.assignments.map(a=>{const sec=sectionById(a.sectionId);const w=Number(a.weeklyPeriods);return`<tr><td>${safe(a.subject)}</td><td>${safe(sec?.label||a.sectionLabel||'غير محدد')}</td><td>${ar(w)}</td><td>${ar(w*Number(state.settings.weeks))}</td><td>${ar(assignmentCapacity(a))}</td><td><span class="adjustment-inline"><b>${ar(w)}</b><i>←</i><span>${ar(Math.max(0,w-1))} مادة</span><em>+ ١ نشاط</em></span></td><td><button class="icon-button" data-remove-assignment="${a.id}">×</button></td></tr>`}).join('')}</tbody></table>`}
  function refreshAutoSubject(){const sectionId=$('#autoSectionSelect')?.value||'';const select=$('#autoSubjectSelect');const preview=$('#autoPeriodsPreview');const add=$('#addAutoAssignmentBtn');if(!select)return;const subjects=subjectsForSection(sectionId);select.disabled=!subjects.length;select.innerHTML=subjects.length?'<option value="">اختر المادة</option>'+subjects.map(s=>`<option value="${safe(s)}">${safe(s)}</option>`).join(''):'<option value="">لا توجد خطة آلية لهذا الفصل</option>';preview.className='auto-periods-preview empty';preview.innerHTML='<span>الحصص</span><strong>—</strong><small>اختر المادة</small>';add.disabled=true}
  function refreshAutoPeriods(){const sectionId=$('#autoSectionSelect')?.value||'';const subject=$('#autoSubjectSelect')?.value||'';const n=periodsFor(sectionId,subject);const preview=$('#autoPeriodsPreview');const add=$('#addAutoAssignmentBtn');if(n){preview.className='auto-periods-preview ready';preview.innerHTML=`<span>حسب الدليل</span><strong>${ar(n)}</strong><small>حصة أسبوعيًا</small>`;add.disabled=false}else{preview.className='auto-periods-preview empty';preview.innerHTML='<span>الحصص</span><strong>—</strong><small>غير متاحة</small>';add.disabled=true}}

  function runValidation(show=true){const weeks=targetAnnual();const teacherItems=state.teachers.map(t=>{const current=teacherLoad(t);let status='eligible',message='جاهز للدخول في المقارنة';if(t.excluded){status='excluded';message='مستثنى من التوزيع'}else if(!t.name||!t.specialty||!Number(t.load)){status='error';message='بيانات المعلم غير مكتملة'}else if(!t.assignments.length){status='error';message='لا توجد إسنادات'}else if(current!==Number(t.load)){status='warning';message=`الإسناد ${current} من ${t.load}`}else if(Number(t.load)!==Number(state.settings.targetLoad)){status='warning';message=`النصاب ليس ${state.settings.targetLoad}`}return{teacherId:t.id,teacherName:t.name,specialty:t.specialty,rank:t.rank,targetLoad:Number(t.load||0),currentLoad:current,status,message}});
    const sectionItems=allSections().map(section=>{const plan=planForGrade(section.gradeId);if(!plan)return{sectionId:section.id,sectionLabel:section.label,status:'unsupported',capacity:0,required:weeks,message:'تحديد مسار وفصل دراسي مطلوب'};if(plan.activity>0)return{sectionId:section.id,sectionLabel:section.label,status:'built-in',capacity:0,required:0,message:`الخطة تتضمن ${plan.activity} حصة نشاط أسبوعيًا`};const candidates=[];state.teachers.filter(t=>!t.excluded).forEach(t=>(t.assignments||[]).filter(a=>a.sectionId===section.id).forEach(a=>candidates.push({teacherId:t.id,capacity:assignmentCapacity(a)})));const cap=candidates.reduce((s,x)=>s+x.capacity,0);return{sectionId:section.id,sectionLabel:section.label,status:cap>=weeks?'eligible':'error',capacity:cap,required:weeks,message:cap>=weeks?'جاهز للتوزيع':`الرصيد ${cap} أقل من ${weeks}`}});
    state.validation={teachers:teacherItems,sections:sectionItems};renderValidation();updateNav();scheduleSave();if(show){const ok=sectionItems.filter(x=>x.status==='eligible').length;toast(`اكتمل التحقق: ${ar(ok)} فصلًا جاهزًا للتوزيع`,ok?'success':'warning')}}
  function renderValidation(){const root=$('#validationTable'),sum=$('#validationSummary');const t=state.validation?.teachers||[],s=state.validation?.sections||[];if(!t.length&&!s.length){sum.innerHTML='';root.className='table-wrap empty-table';root.innerHTML='<div class="empty-icon">✓</div><h3>شغّل التحقق بعد اكتمال الإسنادات</h3><p>سيُفحص المعلمون ثم كل فصل يحتاج حصة نشاط.</p>';return}const eligible=s.filter(x=>x.status==='eligible').length,problems=s.filter(x=>['error','unsupported'].includes(x.status)).length,excluded=t.filter(x=>x.status==='excluded').length;sum.innerHTML=[['المعلمون',t.length,''],['الفصول الجاهزة',eligible,'success'],['فصول تحتاج مراجعة',problems,'warning'],['معلمون مستثنون',excluded,'']].map(([l,v,c])=>`<div class="validation-summary-card ${c}"><span>${l}</span><strong>${ar(v)}</strong></div>`).join('');root.className='validation-groups';root.innerHTML=`<section><div class="subsection-heading"><div><h3>المعلمون</h3><p>اكتمال النصاب وحالة الاستثناء.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>المعلم</th><th>التخصص</th><th>الرتبة</th><th>النصاب</th><th>المسند</th><th>الحالة</th></tr></thead><tbody>${t.map(x=>`<tr><td>${safe(x.teacherName)}</td><td>${safe(x.specialty)}</td><td>${safe(RANKS[x.rank]||'معلم ممارس')}</td><td>${ar(x.targetLoad)}</td><td>${ar(x.currentLoad)}</td><td><span class="status-chip status-${x.status==='eligible'?'complete':x.status==='excluded'?'neutral':x.status}">${safe(x.message)}</span></td></tr>`).join('')}</tbody></table></div></section><section><div class="subsection-heading"><div><h3>الفصول</h3><p>الرصيد المتاح من جميع المعلمين والتخصصات.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>الفصل</th><th>الرصيد المتاح</th><th>المطلوب</th><th>الحالة</th></tr></thead><tbody>${s.map(x=>`<tr><td>${safe(x.sectionLabel)}</td><td>${ar(x.capacity)}</td><td>${ar(x.required)}</td><td><span class="status-chip status-${x.status==='eligible'||x.status==='built-in'?'complete':x.status==='unsupported'?'warning':'error'}">${safe(x.message)}</span></td></tr>`).join('')}</tbody></table></div></section>`}

  function specialtyMatch(specialty,subject){const k=key(canonicalSpecialty(specialty));const q=key(subject);return q.includes(k)||k.includes(q)||((k.includes('اسلام')||k.includes('قران'))&&q.includes('القران'))}
  function generateDistributions(){runValidation(false);const ready=new Set((state.validation.sections||[]).filter(x=>x.status==='eligible').map(x=>x.sectionId));if(!ready.size)return toast('لا توجد فصول جاهزة للتوزيع. راجع الإسنادات أولًا.','warning');const teacherUse=new Map();const assignmentUse=new Map();const results=[];const activeTeachers=state.teachers.filter(t=>!t.excluded&&teacherComplete(t));for(const section of allSections().filter(s=>ready.has(s.id))){const candidates=[];activeTeachers.forEach(t=>(t.assignments||[]).filter(a=>a.sectionId===section.id).forEach(a=>candidates.push({id:a.id,teacherId:t.id,teacherName:t.name,specialty:t.specialty,subject:a.subject,weeklyPeriods:Number(a.weeklyPeriods),capacity:assignmentCapacity(a)})));const weeks=[];let previousSubject='';for(let week=1;week<=targetAnnual();week++){const available=candidates.filter(c=>(assignmentUse.get(c.id)||0)<c.capacity);if(!available.length)break;available.sort((a,b)=>{const au=assignmentUse.get(a.id)||0,bu=assignmentUse.get(b.id)||0;const at=teacherUse.get(a.teacherId)||0,bt=teacherUse.get(b.teacherId)||0;const aratio=au/a.capacity,bratio=bu/b.capacity;const repeatA=a.subject===previousSubject?1:0,repeatB=b.subject===previousSubject?1:0;const matchA=specialtyMatch(a.specialty,a.subject)?0:-.08,matchB=specialtyMatch(b.specialty,b.subject)?0:-.08;return(aratio+repeatA*.6+at*.01+matchA)-(bratio+repeatB*.6+bt*.01+matchB)});const c=available[0];assignmentUse.set(c.id,(assignmentUse.get(c.id)||0)+1);teacherUse.set(c.teacherId,(teacherUse.get(c.teacherId)||0)+1);previousSubject=c.subject;weeks.push({week,teacherId:c.teacherId,teacherName:c.teacherName,specialty:c.specialty,subject:c.subject,weeklyPeriods:c.weeklyPeriods,capacity:c.capacity})}const grouped=new Map();weeks.forEach(w=>{const k=`${w.teacherId}|${w.subject}`;const x=grouped.get(k)||{teacherId:w.teacherId,teacherName:w.teacherName,subject:w.subject,weeklyPeriods:w.weeklyPeriods,used:0,capacity:w.capacity};x.used++;grouped.set(k,x)});results.push({id:uid('distribution'),sectionId:section.id,sectionLabel:section.label,weeks,summary:[...grouped.values()],complete:weeks.length===targetAnnual()})}state.distributions=results;renderDistributions();renderDashboard();updateNav();scheduleSave();const complete=results.filter(x=>x.complete).length;toast(`تم توزيع حصة النشاط على ${ar(complete)} فصلًا`,'success')}
  function renderDistributions(){const root=$('#distributionResults');if(!state.distributions.length){root.className='distribution-results empty-state panel';root.innerHTML='<div class="empty-icon activity-empty">●</div><h3>لم يتم إنشاء توزيع بعد</h3><p>يتحقق النظام من جميع المعلمين والتخصصات ثم يختار المادة المختصر منها لكل فصل.</p>';return}root.className='distribution-results panel';const teacherTotals=new Map();state.distributions.flatMap(x=>x.weeks).forEach(w=>teacherTotals.set(w.teacherName,(teacherTotals.get(w.teacherName)||0)+1));root.innerHTML=`<div class="global-distribution-summary"><div><span class="section-kicker">نتيجة المقارنة الشاملة</span><h3>توزيع حسب الفصول لا حسب كل معلم منفردًا</h3><p>تمت مقارنة المعلمين وتخصصاتهم وإسناداتهم، مع عدم تجاوز حد ١٠٪ لأي إسناد.</p></div><div class="global-metrics"><span><strong>${ar(state.distributions.length)}</strong> فصل</span><span><strong>${ar(state.distributions.reduce((s,x)=>s+x.weeks.length,0))}</strong> حصة نشاط</span><span><strong>${ar(teacherTotals.size)}</strong> معلم مشارك</span></div></div>${state.distributions.map(item=>`<article class="section-distribution-card"><div class="distribution-card-head"><div><span class="section-kicker">الفصل المستفيد</span><h3>${safe(item.sectionLabel)}</h3><p>${item.complete?'تم إنشاء ٣٦ حصة نشاط':'التوزيع غير مكتمل'}</p></div><span class="status-chip ${item.complete?'status-complete':'status-error'}">${item.complete?'جاهز':'ناقص'}</span></div><div class="distribution-body section-result-body"><div><div class="subsection-heading"><div><h3>المادة المختصر منها والفرق</h3><p>ملخص المواد والمعلمين الذين تحولت حصصهم إلى نشاط.</p></div></div><div class="source-summary-list">${item.summary.map(x=>`<div class="source-summary-item"><div><strong>${safe(x.subject)}</strong><small>${safe(x.teacherName)} · مستخدم ${ar(x.used)} من ${ar(x.capacity)}</small></div><div class="adjustment-equation"><b>${ar(x.weeklyPeriods)}</b><i>←</i><span>${ar(Math.max(0,x.weeklyPeriods-1))} مادة</span><em>+ ١ نشاط</em><u>الفرق -١ / +١</u></div></div>`).join('')}</div></div><div><div class="subsection-heading"><div><h3>التوزيع على أسابيع العام</h3><p>المادة التي تُختصر منها حصة في كل أسبوع.</p></div></div><div class="weeks-grid">${item.weeks.map(w=>`<div class="week-item"><strong>الأسبوع ${ar(w.week)}</strong><span>${safe(w.subject)}</span><small>${safe(w.teacherName)}</small><div class="week-difference">${ar(w.weeklyPeriods)} ← ${ar(Math.max(0,w.weeklyPeriods-1))} مادة + ١ نشاط</div></div>`).join('')}</div></div></div></article>`).join('')}`}

  function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${(state.settings.schoolName||'مشروع-النشاط').replace(/\s+/g,'-')}-نسخة-احتياطية.json`;a.click();URL.revokeObjectURL(url);toast('تم إنشاء النسخة الاحتياطية','success')}
  async function restore(file){try{state=mergeState(JSON.parse(await file.text()));await persist();renderAll();toast('تمت استعادة النسخة','success')}catch(e){console.error(e);toast('ملف النسخة غير صالح','error')}}
  async function clearBrowserData(){if(!confirm('سيتم حذف جميع بيانات المدرسة والمعلمين والتوزيعات من هذا المتصفح. هل تريد المتابعة؟'))return;try{if(db)db.close();await new Promise(res=>{const q=indexedDB.deleteDatabase(DB_NAME);q.onsuccess=q.onerror=q.onblocked=()=>res()});localStorage.removeItem('activity10State');localStorage.removeItem('activity10SidebarCollapsed');location.reload()}catch(e){console.error(e);toast('تعذر مسح البيانات','error')}}
  function downloadTemplate(){const rows=[['المعرف','اسم المعلم','رقم الجوال','الحالة','الوظيفة','التخصص','مادة التخصص','النصاب'],['Tea_1017100908','أحمد سعد أحمد الغامدي','966530237122','دائم','معلم','دين','دين','']];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='نموذج-استيراد-المعلمين.csv';a.click();URL.revokeObjectURL(url)}

  const mobileMedia=matchMedia('(max-width:900px)');
  function closeMobile(){$('.app-shell')?.classList.remove('sidebar-mobile-open');document.body.classList.remove('mobile-menu-open');$('#mobileMenuBtn')?.setAttribute('aria-expanded','false')}
  function applySidebar(collapsed){if(mobileMedia.matches)return;$('.app-shell').classList.toggle('sidebar-collapsed',collapsed);$('.sidebar').classList.toggle('collapsed',collapsed);localStorage.setItem('activity10SidebarCollapsed',collapsed?'1':'0')}

  function bind(){
    const clearBtn=document.createElement('button');clearBtn.id='clearBrowserDataBtn';clearBtn.className='danger-sidebar-button full-width';clearBtn.textContent='مسح بيانات المتصفح';$('.sidebar-footer').appendChild(clearBtn);
    $('#sideNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)});document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)navigate(b.dataset.go)});$('#quickContinueBtn').addEventListener('click',()=>navigate(settingsComplete()?(state.teachers.length?'classify':'import'):'settings'));
    $('#sidebarToggle').addEventListener('click',()=>{if(mobileMedia.matches)return closeMobile();applySidebar(!$('.app-shell').classList.contains('sidebar-collapsed'))});$('#mobileMenuBtn').addEventListener('click',()=>{$('.app-shell').classList.toggle('sidebar-mobile-open');document.body.classList.toggle('mobile-menu-open')});$('#sidebarBackdrop').addEventListener('click',closeMobile);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobile()});
    $('#schoolNameInput').addEventListener('input',e=>{state.settings.schoolName=e.target.value;updateTopbar();scheduleSave()});$$('[data-choice="gender"]').forEach(b=>b.addEventListener('click',()=>{state.settings.gender=b.dataset.value;renderSettings();scheduleSave()}));$('#stageCards').addEventListener('click',e=>{const tog=e.target.closest('[data-toggle-stage]');if(tog){const k=tog.dataset.toggleStage;state.settings.stages[k].enabled=!state.settings.stages[k].enabled;if(!state.settings.stages[k].enabled)gradeDefinitions[k].forEach(([id])=>delete state.settings.gradeSections[id]);renderSettings();scheduleSave();return}const type=e.target.closest('[data-stage-type]');if(type){state.settings.stages[type.dataset.stageType].type=type.dataset.type;renderSettings();scheduleSave()}});$('#gradesEditor').addEventListener('input',e=>{const i=e.target.closest('[data-grade-count]');if(i){state.settings.gradeSections[i.dataset.gradeCount]=Math.max(0,Number(i.value||0));renderSettings();scheduleSave()}});['regularPeriodsInput','targetLoadInput','weeksInput','activityWeeklyInput'].forEach(id=>$('#'+id).addEventListener('input',e=>{const m={regularPeriodsInput:'regularPeriods',targetLoadInput:'targetLoad',weeksInput:'weeks',activityWeeklyInput:'activityWeekly'};state.settings[m[id]]=Math.max(1,Number(e.target.value||1));renderDiagnostic();scheduleSave()}));$$('.wizard-step').forEach(b=>b.addEventListener('click',()=>showSettingsStep(b.dataset.settingsStep)));$('#settingsPrevBtn').addEventListener('click',()=>showSettingsStep(state.settings.currentStep-1));$('#settingsNextBtn').addEventListener('click',()=>{const err=validateSettings(state.settings.currentStep);if(err)return toast(err,'warning');if(state.settings.currentStep===4){scheduleSave();toast('تم حفظ إعداد المدرسة','success');navigate('import')}else showSettingsStep(state.settings.currentStep+1)});
    $$('.import-tab').forEach(b=>b.addEventListener('click',()=>{$$('.import-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.import-tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.importPanel===b.dataset.importTab))}));$('#parseTextBtn').addEventListener('click',()=>{state.importPreview=parseText($('#teachersTextInput').value);renderImportPreview();scheduleSave();toast(`تمت قراءة ${ar(state.importPreview.length)} سجلًا`,'success')});$('#excelInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)openMapping(f)});const dz=$('#dropZone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)openMapping(f)});['mapNameColumn','mapSpecialtyColumn','mapLoadColumn'].forEach(id=>$('#'+id).addEventListener('change',renderMapSample));$('#confirmMappingBtn').addEventListener('click',confirmMapping);$('#downloadTemplateBtn').addEventListener('click',downloadTemplate);$('#normalizePreviewBtn').addEventListener('click',()=>{state.importPreview.forEach(x=>{x.name=clean(x.name);x.specialty=canonicalSpecialty(x.specialty)});renderImportPreview();scheduleSave()});$('#removeDuplicatePreviewBtn').addEventListener('click',()=>{const seen=new Set();state.importPreview=state.importPreview.filter(x=>{const k=key(x.name);if(seen.has(k))return false;seen.add(k);return true});renderImportPreview();scheduleSave()});$('#importPreview').addEventListener('input',e=>{const i=e.target.closest('[data-preview-field]');if(!i)return;const x=state.importPreview.find(v=>v.tempId===i.dataset.previewId);if(!x)return;x[i.dataset.previewField]=i.dataset.previewField==='load'?(i.value?Number(i.value):null):i.value;x.status=!x.name?'error':!x.specialty||!Number(x.load)?'warning':'complete';renderImportPreview();scheduleSave()});$('#clearPreviewBtn').addEventListener('click',()=>{state.importPreview=[];renderImportPreview();scheduleSave()});$('#commitImportBtn').addEventListener('click',commitImport);
    $('#teacherSearch').addEventListener('input',renderTeachers);$('#teachersList').addEventListener('click',e=>{const b=e.target.closest('[data-select-teacher]');if(b)selectTeacher(b.dataset.selectTeacher)});$('#teacherEditor').addEventListener('change',e=>{if(e.target.id==='autoSectionSelect')return refreshAutoSubject();if(e.target.id==='autoSubjectSelect')return refreshAutoPeriods()});$('#teacherEditor').addEventListener('click',e=>{const t=state.teachers.find(x=>x.id===state.selectedTeacherId);if(!t)return;const remove=e.target.closest('[data-remove-assignment]');if(remove){t.assignments=t.assignments.filter(a=>a.id!==remove.dataset.removeAssignment);renderTeacherEditor(t.id);renderTeachers();scheduleSave();return}if(e.target.closest('#addAutoAssignmentBtn')){const sectionId=$('#autoSectionSelect').value,subject=$('#autoSubjectSelect').value,n=periodsFor(sectionId,subject);if(!sectionId||!subject||!n)return toast('اختر الفصل والمادة.','warning');if(t.assignments.some(a=>a.sectionId===sectionId&&a.subject===subject))return toast('هذا الإسناد موجود مسبقًا.','warning');t.assignments.push({id:uid('assignment'),sectionId,sectionLabel:sectionById(sectionId)?.label,subject,weeklyPeriods:n});renderTeacherEditor(t.id);renderTeachers();renderDashboard();updateNav();scheduleSave();toast(`تمت إضافة ${subject} بعدد ${n} حصص`,'success');return}if(e.target.closest('[data-action="save-teacher"]')){t.name=clean($('[data-teacher-field="name"]').value);t.specialty=canonicalSpecialty($('[data-teacher-field="specialty"]').value);t.load=Number($('[data-teacher-field="load"]').value)||null;t.rank=$('[data-teacher-field="rank"]').value;t.excluded=$('[data-teacher-field="excluded"]').checked;renderTeachers();renderDashboard();updateNav();scheduleSave();toast('تم حفظ بيانات المعلم','success');return}if(e.target.closest('[data-action="delete-teacher"]')){if(confirm(`حذف المعلم ${t.name}؟`)){state.teachers=state.teachers.filter(x=>x.id!==t.id);state.selectedTeacherId=null;renderTeachers();renderDashboard();updateNav();scheduleSave()}}});
    $('#runValidationBtn').addEventListener('click',()=>runValidation(true));$('#generateDistributionBtn').addEventListener('click',generateDistributions);$('#clearDistributionBtn').addEventListener('click',()=>{state.distributions=[];renderDistributions();updateNav();scheduleSave();toast('تم مسح نتائج التوزيع','success')});$('#backupBtn').addEventListener('click',backup);$('#restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)restore(f);e.target.value=''});clearBtn.addEventListener('click',clearBrowserData);
  }

  function renderAll(){updateTopbar();renderDashboard();renderSettings();renderImportPreview();renderTeachers();renderValidation();renderDistributions();updateNav();navigate(state.currentView||'dashboard')}
  async function init(){try{db=await openDB();const saved=await readState();if(saved)state=mergeState(saved)}catch(e){console.error(e);storageMode='localstorage';state=mergeState(await readState())}bind();applySidebar(!mobileMedia.matches&&localStorage.getItem('activity10SidebarCollapsed')==='1');renderAll()}
  document.addEventListener('DOMContentLoaded',init);
})();
